# This is a basic workflow to help you get started with Actions
name: Appdome Fuse

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # A demo job that builds an application to use with appdome
  build_app:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@master
        with:
          path: main
          
     # Cloning appdome-api-python github repository
      - name: Cloning appdome-api-python github repository
        uses: actions/checkout@master
        with:
          repository: Appdome/appdome-api-python
          ref: refs/heads/main
          path: appdome

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Building my app

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Build app
          echo sign app
          ls main
          pwd
      
      # Run appdome api script
      - name: Fuse with appdome
        env:
          APPDOME_API_KEY: ${{ secrets.APPDOME_API_KEY }}
          APPDOME_TEAM_ID: ${{ secrets.APPDOME_TEAM_ID }}
          APPDOME_ANDROID_FS_ID: ${{ secrets.APPDOME_ANDROID_FS_ID }}
        run: |
          pwd
          ls appdome
          mkdir outputs
          python3 appdome/appdome-api-python/appdome_api.py --app main/demo_app.apk --sign_on_appdome --keystore main/key.keystore \
              --keystore_pass pass --keystore_alias alias --key_pass k_pass --output outputs/fused_app.apk --certificate_output outputs/certificate.pdf
    
          

