name: Appdome build-2secure

on:
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  appdome:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: Appdome build-2secure
        uses: Appdome/github_build-2secure@1.0
        with:
          # Appdome API key
          APPDOME_API_TOKEN: ${{secrets.APPDOME_API_KEY}}
          # APK file
          APP_FILE: "./app-release.apk"
          # Appdome FusionSetId iOS/Android
          FUSION_SET_ID: "fb04d100-91ad-11ed-bcff-897df33224f0"
          # iOS/Android Signin option
          SIGN_OPTIONS: "PRIVATE_SIGNING"
          # signing sha1 fingerprint
          SIGN_FINGERPRINT: ${{secrets.SHA1}}


