name: Appdome build-2secure

on:
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  appdome:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
        with:
          path: main
        
      - name: Appdome build-2secure
        uses: Appdome/github_build-2secure@1.0
        with:
          # Appdome API key
          APPDOME_API_TOKEN: ${{secrets.APPDOME_API_KEY}}
          # APK file
          APP_FILE: "https://github.com/avi112211/GitHub_action_test/raw/main/app-release.apk"
          # Appdome FusionSetId iOS/Android
          FUSION_SET_ID: ${{vars.APPDOME_ANDROID_FS_ID}}
          # iOS/Android Signin option
          SIGN_OPTIONS: "PRIVATE_SIGNING"
          # signing sha1 fingerprint
          SIGN_FINGERPRINT: ${{secrets.SHA1}}


